<?php

function escapia_menu() {
  $items = array();

  $items['admin/structure/escapia'] = array(
    'title' => t('Escapia Management'),
    'description' => 'Configure EscapiaNET connections and properties.',
    'access callback' => 'user_access',
    'access arguments' => array('configure escapia'),
    'page callback' => 'escapia_management_page',
    'file' => 'includes/escapia.admin.inc',
  );

  return $items;
}